import NavBar from "@/components/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import { navLinks } from "@/utils/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className="w-full max-w-5xl items-center justify-between font-mono text-sm ">
            <div className="fixed left-0 top-0 flex items-center justify-between h-16 w-full justify-center  ">
              <Image
                src="/logo.png"
                alt="Gama Logo"
                width={100}
                height={24}
                priority
              />
              <NavBar navLinks={navLinks} />
            </div>
            <div className="fixed bottom-0 left-0 flex h-48 w-full items-end justify-center ">
              <a
                className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
                href="https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                By{" Hugo Gama in "}
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  className="dark:invert"
                  width={100}
                  height={24}
                  priority
                />
              </a>
            </div>
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
